language: php

php:
    - 7.0
    - 7.1

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer selfupdate
    - composer update --prefer-dist --no-interaction

script:
    - vendor/bin/phpstan analyse -l 7 -c phpstan.neon src Tests
    - vendor/bin/phpunit
